// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Inventario.Models;

#nullable disable

namespace Proyecto_Inventario.Migrations
{
    [DbContext(typeof(InventarioContext))]
    [Migration("20230520164122_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Proyecto_Inventario.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("Precio")
                        .HasColumnType("int")
                        .HasColumnName("precio");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Codigo" }, "codigo")
                        .IsUnique();

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("Proyecto_Inventario.Models.ProductoSucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdProducto" }, "producto");

                    b.HasIndex(new[] { "IdSucursal" }, "sucursal");

                    b.ToTable("producto_sucursal", (string)null);
                });

            modelBuilder.Entity("Proyecto_Inventario.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("sucursal", (string)null);
                });

            modelBuilder.Entity("Proyecto_Inventario.Models.ProductoSucursal", b =>
                {
                    b.HasOne("Proyecto_Inventario.Models.Producto", "IdProductoNavigation")
                        .WithMany("ProductoSucursals")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("producto");

                    b.HasOne("Proyecto_Inventario.Models.Sucursal", "IdSucursalNavigation")
                        .WithMany("ProductoSucursals")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("sucursal");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("Proyecto_Inventario.Models.Producto", b =>
                {
                    b.Navigation("ProductoSucursals");
                });

            modelBuilder.Entity("Proyecto_Inventario.Models.Sucursal", b =>
                {
                    b.Navigation("ProductoSucursals");
                });
#pragma warning restore 612, 618
        }
    }
}
